apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: vlan-interfaces
    valuesInline:
      vlan_ids:
        - 210
        - 211
      parent_interfaces:
        - eno1
        - enp4s0f0np0
        - enp5s0f0np0
        - enp65s0f0np0
        - enp65s0f1np1
